function [outInfo, outLatex] = printInfo(BODY_FORMAT, BODY_LATEX, name, ...
    RANGE, solver)
% Console output
outInfo = sprintf(BODY_FORMAT, name, RANGE, solver.iter, ...
    solver.nObjFunc, solver.nGrad, solver.nHess, solver.pgNorm, ...
    solver.solveTime);

% LaTeX template
outLatex = sprintf(BODY_LATEX, name, ' & ', RANGE, ' & ', solver.iter, ...
    ' & ', solver.nObjFunc, ' & ', solver.nGrad, ' & ', solver.nHess, ...
    ' & ', solver.pgNorm, ' & ', solver.solveTime, ' \\ ');
end